spring:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      uri: mongodb://mo2222_workout:kO-TBI9_!$yJaVK7uT9zYkXL1r1lwy@mongo2.small.pl/mo2222_workout?retryWrites=true&w=majority&tls=false&tlsAllowInvalidCertificates=true
  datasource:
    username: p2222_food
    password: 9bJpou&'X99BGfT?.Z18h6jVSBk8cK
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://pgsql2.small.pl/p2222_food
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml

server:
  port: 37786
  ssl:
    key-store: /home/mutarexx/domains/mutarexx.smallhost.pl/certs/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: alias_name

path:
  file:
    excel: /home/mutarexx/tmp/

google:
  credentials:
    folder:
      path: file:/home/mutarexx/domains/mutarexx.smallhost.pl/google_token/serviceAccount.json

app:
  frontend:
    url: https://mutarexx.smallhost.pl